spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: adminpass
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver

  # https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true